### ISSUE TITLE
Add manual message ack

### ISSUE THREAD

**Issue by pauldeng** [MeowWolf/node-red-contrib-amqp#8]
Hi mate,

Great work, thanks for sharing this.

I am just wondering if you can add [manual message ack capability](https://www.rabbitmq.com/tutorials/tutorial-two-javascript.html)?
`
channel.ack(msg);  
`

This is a very useful feature which is missing in abreits amqp node.

Maybe a new amqp-ack node can be introduced?
![Image of ack](https://dengpeng.de/wp-content/uploads/2020/01/amqp-ack-sample-flow.png)

Cheers,
Paul

**Comment by amodelbello** [comment]
Hi @pauldeng thanks a lot for the interest. You can specify noAck true/false in the node config (albeit this feature has not seen a lot of testing) :
<img width="630" alt="Screen Shot 2020-01-22 at 9 05 04 AM" src="https://user-images.githubusercontent.com/2342804/72911006-99e89780-3cf6-11ea-9d59-e052b73fb4e3.png">

Or am I misunderstanding the request?

**Comment by pauldeng** [comment]
Hi mate,

Thanks for the reply. Correct if I am wrong.

If the noAck is unchecked in the amqp-in node, the process steps are below. This logic guarantees that a message is successfully delivered from RabbitMQ to Node-Red.
1. this.node.send(msg); // line 59 of Amqp.js
2. this.channel.ack(msg); // line 62 of Amqp.js

What I am thinking of is to guarantees the process of the message. It means we have to acknowledge RabbitMQ manually after the message is processed. For example, I will manually ack after some functions are applied in the amqp-ack node:
![Image of ack](https://dengpeng.de/wp-content/uploads/2020/01/amqp-ack-sample-flow.png)  
If the node-red crash in the middle of the process, the message will be re-queued by RabbitMQ and never lost

Please check out the "Message acknowledgment" section of https://www.rabbitmq.com/tutorials/tutorial-two-javascript.html

Cheers,
Paul

**Comment by amodelbello** [comment]
Got it. I'll take a look.

**Comment by amodelbello** [comment]
I like this idea and I'd like to try to figure out a way to implement it. However it's not as simple as just adding a node to ack the message:

> Acknowledgement must be sent on the same channel that received the delivery. Attempts to acknowledge using a different channel will result in a channel-level protocol exception.

The channel is not accessible from outside the node. In order to get around this I think we can have the in/out nodes take an "ack" field on an input payload that when true could fire the channel.ack() method. Something like this:

![nodes-edit](https://user-images.githubusercontent.com/2342804/73000610-56596080-3dbe-11ea-97f4-dc7ad4a6c8f5.png)


This would not be a trivial change but I think it'd be worth taking a stab at it.
